import type { ClubEraPool, Seed } from "./types";
const f = (name: string, positions: string[], rating: number, goals: number, assists: number, cleanSheets = 0): Seed => ({ name, positions, rating, stats: positions.includes("GK") ? { goals: 0, assists: 0, cleanSheets } : { goals, assists } });
/** EPL expansion clubs — 6 players per era */
export const FOOTBALL_EPL_EXTRA: ClubEraPool = {
  "Leeds United": {
    "1990s": [
      f("Lucas Radebe", ["CB","DF"], 86, 2, 1),
      f("Gary Speed", ["CM","MF"], 86, 8, 6),
      f("Tony Yeboah", ["ST","FW"], 85, 16, 4),
      f("Nigel Martyn", ["GK"], 85, 0, 0, 13),
      f("Lee Bowyer", ["CM","MF"], 83, 6, 5),
      f("Harry Kewell", ["LW","FW"], 86, 10, 8),
    ],
    "2000s": [
      f("Mark Viduka", ["ST","FW"], 86, 18, 5),
      f("Harry Kewell", ["LW","FW"], 85, 10, 8),
      f("Jonathan Woodgate", ["CB","DF"], 84, 2, 1),
      f("Paul Robinson", ["GK"], 85, 0, 0, 14),
      f("Alan Smith", ["ST","FW"], 83, 10, 4),
      f("Olivier Dacourt", ["CM","MF"], 84, 5, 5),
    ],
    "2010s": [
      f("Pablo Hernandez", ["CM","MF"], 82, 5, 6),
      f("Kemar Roofe", ["ST","FW"], 81, 12, 3),
      f("Liam Cooper", ["CB","DF"], 80, 2, 1),
      f("Illan Meslier", ["GK"], 80, 0, 0, 10),
      f("Patrick Bamford", ["ST","FW"], 83, 14, 3),
      f("Raphinha", ["RW","FW"], 84, 10, 6),
    ],
    "2020s": [
      f("Patrick Bamford", ["ST","FW"], 84, 14, 4),
      f("Raphinha", ["RW","FW"], 86, 12, 8),
      f("Kalvin Phillips", ["CM","MF"], 85, 3, 5),
      f("Illan Meslier", ["GK"], 83, 0, 0, 11),
      f("Rodrigo", ["ST","FW"], 83, 12, 3),
      f("Pascal Struijk", ["CB","DF"], 82, 2, 1),
    ],
  },
  "Everton": {
    "1990s": [
      f("Duncan Ferguson", ["ST","FW"], 84, 14, 3),
      f("Neville Southall", ["GK"], 88, 0, 0, 15),
      f("Tony Hibbert", ["RB","DF"], 82, 1, 3),
      f("Nick Barmby", ["CM","MF"], 83, 8, 6),
      f("Gary Speed", ["CM","MF"], 85, 6, 5),
      f("Daniel Amokachi", ["ST","FW"], 82, 10, 4),
    ],
    "2000s": [
      f("Tim Cahill", ["CM","MF"], 86, 10, 4),
      f("Mikel Arteta", ["CM","MF"], 85, 6, 8),
      f("Phil Neville", ["RB","DF"], 84, 2, 4),
      f("Tim Howard", ["GK"], 86, 0, 0, 14),
      f("James Beattie", ["ST","FW"], 83, 12, 3),
      f("Andy Johnson", ["ST","FW"], 84, 14, 3),
    ],
    "2010s": [
      f("Romelu Lukaku", ["ST","FW"], 88, 20, 5),
      f("Leighton Baines", ["LB","DF"], 86, 3, 8),
      f("Tim Howard", ["GK"], 85, 0, 0, 13),
      f("Ross Barkley", ["CM","MF"], 85, 8, 8),
      f("Phil Jagielka", ["CB","DF"], 84, 3, 1),
      f("Gylfi Sigurdsson", ["CM","MF"], 84, 8, 8),
    ],
    "2020s": [
      f("Dominic Calvert-Lewin", ["ST","FW"], 84, 14, 3),
      f("Jordan Pickford", ["GK"], 85, 0, 0, 12),
      f("James Tarkowski", ["CB","DF"], 84, 2, 1),
      f("Abdoulaye Doucoure", ["CM","MF"], 83, 5, 4),
      f("Anthony Gordon", ["LW","FW"], 83, 8, 5),
      f("Amadou Onana", ["CM","MF"], 83, 4, 4),
    ],
  },
  "West Ham": {
    "1990s": [
      f("Paolo Di Canio", ["ST","FW"], 86, 14, 8),
      f("Trevor Sinclair", ["RW","FW"], 84, 10, 6),
      f("Julian Dicks", ["LB","DF"], 82, 4, 3),
      f("Shaka Hislop", ["GK"], 83, 0, 0, 12),
      f("Frank Lampard", ["CM","MF"], 84, 8, 6),
      f("Joe Cole", ["LW","FW"], 85, 8, 8),
    ],
    "2000s": [
      f("Carlos Tevez", ["ST","FW"], 87, 16, 5),
      f("Mark Noble", ["CM","MF"], 83, 5, 5),
      f("Matthew Upson", ["CB","DF"], 82, 2, 1),
      f("Robert Green", ["GK"], 84, 0, 0, 12),
      f("Craig Bellamy", ["ST","FW"], 84, 12, 4),
      f("Scott Parker", ["CM","MF"], 85, 4, 5),
    ],
    "2010s": [
      f("Dimitri Payet", ["CM","MF"], 87, 10, 12),
      f("Mark Noble", ["CM","MF"], 83, 4, 5),
      f("Adrian", ["GK"], 83, 0, 0, 11),
      f("Andy Carroll", ["ST","FW"], 83, 12, 3),
      f("Cheikhou Kouyate", ["CM","MF"], 83, 5, 3),
      f("Michail Antonio", ["RW","FW"], 84, 10, 6),
    ],
    "2020s": [
      f("Jarrod Bowen", ["RW","FW"], 85, 14, 6),
      f("Declan Rice", ["CM","MF"], 88, 4, 4),
      f("Lukasz Fabianski", ["GK"], 83, 0, 0, 11),
      f("Michail Antonio", ["ST","FW"], 83, 12, 4),
      f("Lucas Paqueta", ["CM","MF"], 85, 6, 8),
      f("Kurt Zouma", ["CB","DF"], 84, 2, 1),
    ],
  },
  "Brighton": {
    "1990s": [
      f("Kerry Mayo", ["CB","DF"], 78, 1, 1),
      f("Mark Walton", ["GK"], 77, 0, 0, 9),
      f("Darren Freeman", ["ST","FW"], 77, 8, 2),
      f("Ian Chapman", ["CM","MF"], 76, 4, 3),
      f("John Robinson", ["CM","MF"], 77, 5, 4),
      f("Andy McLaren", ["ST","FW"], 76, 7, 2),
    ],
    "2000s": [
      f("Bobby Zamora", ["ST","FW"], 82, 12, 4),
      f("Matthew Upson", ["CB","DF"], 81, 2, 1),
      f("Paul Robinson", ["GK"], 80, 0, 0, 10),
      f("Leonardo Ulloa", ["ST","FW"], 80, 10, 3),
      f("Bruno", ["CB","DF"], 81, 2, 1),
      f("Beram Kayal", ["CM","MF"], 79, 4, 4),
    ],
    "2010s": [
      f("Glenn Murray", ["ST","FW"], 83, 14, 3),
      f("Lewis Dunk", ["CB","DF"], 84, 3, 1),
      f("Mat Ryan", ["GK"], 84, 0, 0, 12),
      f("Pascal Gross", ["CM","MF"], 83, 6, 8),
      f("Shane Duffy", ["CB","DF"], 82, 2, 1),
      f("Jose Izquierdo", ["LW","FW"], 81, 8, 4),
    ],
    "2020s": [
      f("Moisés Caicedo", ["CM","MF"], 86, 4, 4),
      f("Kaoru Mitoma", ["LW","FW"], 85, 10, 6),
      f("Robert Sanchez", ["GK"], 84, 0, 0, 12),
      f("Alexis Mac Allister", ["CM","MF"], 86, 8, 8),
      f("Lewis Dunk", ["CB","DF"], 85, 2, 1),
      f("Evan Ferguson", ["ST","FW"], 83, 12, 3),
    ],
  },
  "Wolves": {
    "1990s": [
      f("Steve Bull", ["ST","FW"], 84, 16, 4),
      f("Derek Parkin", ["CB","DF"], 80, 2, 1),
      f("Mike Marsh", ["CM","MF"], 79, 5, 4),
      f("Andy Thompson", ["GK"], 78, 0, 0, 9),
      f("Don Goodman", ["ST","FW"], 81, 12, 3),
      f("Kevin Muscat", ["RB","DF"], 79, 2, 3),
    ],
    "2000s": [
      f("Matt Murray", ["GK"], 81, 0, 0, 11),
      f("Joleon Lescott", ["CB","DF"], 83, 3, 1),
      f("Carl Fletcher", ["CM","MF"], 80, 4, 4),
      f("Kenny Miller", ["ST","FW"], 81, 10, 3),
      f("Michael Kightly", ["LW","FW"], 80, 8, 5),
      f("Stephen Ward", ["LB","DF"], 80, 3, 4),
    ],
    "2010s": [
      f("Raul Jimenez", ["ST","FW"], 86, 18, 5),
      f("Ruben Neves", ["CM","MF"], 85, 6, 6),
      f("Rui Patricio", ["GK"], 85, 0, 0, 13),
      f("Willy Boly", ["CB","DF"], 83, 2, 1),
      f("Diogo Jota", ["LW","FW"], 84, 12, 5),
      f("Joao Moutinho", ["CM","MF"], 84, 4, 8),
    ],
    "2020s": [
      f("Matheus Cunha", ["ST","FW"], 85, 14, 5),
      f("Ruben Neves", ["CM","MF"], 84, 5, 6),
      f("Jose Sa", ["GK"], 84, 0, 0, 12),
      f("Max Kilman", ["CB","DF"], 83, 2, 1),
      f("Pedro Neto", ["RW","FW"], 84, 8, 8),
      f("Hwang Hee-chan", ["LW","FW"], 83, 10, 4),
    ],
  },
  "Crystal Palace": {
    "1990s": [
      f("Chris Coleman", ["CB","DF"], 80, 2, 1),
      f("Nigel Martyn", ["GK"], 84, 0, 0, 12),
      f("Chris Armstrong", ["ST","FW"], 81, 12, 3),
      f("Gareth Southgate", ["CB","DF"], 82, 1, 1),
      f("Attilio Lombardo", ["RW","FW"], 83, 8, 8),
      f("Tomas Brolin", ["ST","FW"], 84, 12, 5),
    ],
    "2000s": [
      f("Andrew Johnson", ["ST","FW"], 83, 14, 3),
      f("Shaun Derry", ["CM","MF"], 80, 4, 4),
      f("Gabor Kiraly", ["GK"], 81, 0, 0, 10),
      f("Clinton Morrison", ["ST","FW"], 81, 12, 3),
      f("Danny Butterfield", ["RB","DF"], 79, 2, 3),
      f("Mark Hudson", ["CB","DF"], 80, 2, 1),
    ],
    "2010s": [
      f("Wilfried Zaha", ["RW","FW"], 86, 12, 8),
      f("Christian Benteke", ["ST","FW"], 84, 14, 3),
      f("Wayne Hennessey", ["GK"], 82, 0, 0, 11),
      f("James McArthur", ["CM","MF"], 82, 5, 4),
      f("Joel Ward", ["RB","DF"], 81, 2, 3),
      f("Yohan Cabaye", ["CM","MF"], 84, 5, 6),
    ],
    "2020s": [
      f("Wilfried Zaha", ["RW","FW"], 85, 10, 6),
      f("Eberechi Eze", ["CM","MF"], 85, 8, 8),
      f("Vicente Guaita", ["GK"], 83, 0, 0, 11),
      f("Marc Guehi", ["CB","DF"], 84, 2, 1),
      f("Michael Olise", ["RW","FW"], 84, 8, 8),
      f("Jean-Philippe Mateta", ["ST","FW"], 83, 12, 3),
    ],
  },
  "Fulham": {
    "1990s": [
      f("Chris Coleman", ["CB","DF"], 79, 2, 1),
      f("Maik Taylor", ["GK"], 80, 0, 0, 10),
      f("Geoff Horsfield", ["ST","FW"], 80, 10, 3),
      f("Lee Clark", ["CM","MF"], 79, 4, 4),
      f("Barry Hayles", ["ST","FW"], 80, 11, 3),
      f("Steve Finnan", ["RB","DF"], 80, 2, 4),
    ],
    "2000s": [
      f("Brian McBride", ["ST","FW"], 83, 12, 4),
      f("Clint Dempsey", ["CM","MF"], 84, 8, 6),
      f("Mark Schwarzer", ["GK"], 84, 0, 0, 12),
      f("Bobby Zamora", ["ST","FW"], 83, 12, 4),
      f("Danny Murphy", ["CM","MF"], 83, 5, 6),
      f("Brede Hangeland", ["CB","DF"], 83, 2, 1),
    ],
    "2010s": [
      f("Aleksandar Mitrovic", ["ST","FW"], 85, 18, 4),
      f("Tom Cairney", ["CM","MF"], 83, 5, 8),
      f("Marcus Bettinelli", ["GK"], 82, 0, 0, 10),
      f("Ryan Sessegnon", ["LB","DF"], 82, 3, 5),
      f("Ivan Cavaleiro", ["LW","FW"], 82, 8, 5),
      f("Tim Ream", ["CB","DF"], 81, 2, 1),
    ],
    "2020s": [
      f("Aleksandar Mitrovic", ["ST","FW"], 84, 16, 3),
      f("Joao Palhinha", ["CM","MF"], 85, 4, 3),
      f("Bernd Leno", ["GK"], 84, 0, 0, 12),
      f("Antonee Robinson", ["LB","DF"], 83, 2, 6),
      f("Andreas Pereira", ["CM","MF"], 83, 6, 6),
      f("Tim Ream", ["CB","DF"], 81, 2, 1),
    ],
  },
  "Bournemouth": {
    "1990s": [
      f("Steve Fletcher", ["ST","FW"], 78, 8, 2),
      f("James Hayter", ["ST","FW"], 77, 7, 2),
      f("Ian Cox", ["CB","DF"], 76, 1, 1),
      f("Neil Moss", ["GK"], 76, 0, 0, 8),
      f("Jamie Redknapp", ["CM","MF"], 80, 4, 5),
      f("Efan Ekoku", ["ST","FW"], 79, 10, 3),
    ],
    "2000s": [
      f("Steve Fletcher", ["ST","FW"], 77, 6, 2),
      f("Darren Anderton", ["CM","MF"], 80, 4, 5),
      f("Neil Moss", ["GK"], 75, 0, 0, 8),
      f("James Hayter", ["ST","FW"], 76, 6, 2),
      f("Shaun Bartlett", ["ST","FW"], 78, 8, 2),
      f("Carl Fletcher", ["CM","MF"], 77, 3, 3),
    ],
    "2010s": [
      f("Callum Wilson", ["ST","FW"], 84, 14, 3),
      f("Ryan Fraser", ["LW","FW"], 83, 6, 8),
      f("Asmir Begovic", ["GK"], 83, 0, 0, 11),
      f("Nathan Ake", ["CB","DF"], 84, 3, 1),
      f("Josh King", ["ST","FW"], 82, 10, 4),
      f("Harry Arter", ["CM","MF"], 81, 3, 4),
    ],
    "2020s": [
      f("Dominic Solanke", ["ST","FW"], 84, 16, 4),
      f("Philip Billing", ["CM","MF"], 83, 6, 4),
      f("Neto", ["GK"], 83, 0, 0, 11),
      f("Lloyd Kelly", ["CB","DF"], 82, 2, 1),
      f("Antoine Semenyo", ["RW","FW"], 83, 10, 5),
      f("Marcus Tavernier", ["LW","FW"], 82, 8, 5),
    ],
  },
  "Nottingham Forest": {
    "1990s": [
      f("Roy Keane", ["CM","MF"], 88, 6, 5),
      f("Des Walker", ["CB","DF"], 85, 2, 1),
      f("Mark Crossley", ["GK"], 83, 0, 0, 12),
      f("Teddy Sheringham", ["ST","FW"], 86, 14, 6),
      f("Stuart Pearce", ["LB","DF"], 86, 4, 4),
      f("Nigel Clough", ["CM","MF"], 84, 8, 6),
    ],
    "2000s": [
      f("Robert Earnshaw", ["ST","FW"], 82, 12, 3),
      f("Michael Dawson", ["CB","DF"], 82, 2, 1),
      f("Paul Smith", ["GK"], 80, 0, 0, 10),
      f("David Johnson", ["ST","FW"], 80, 10, 3),
      f("Andy Reid", ["CM","MF"], 81, 5, 5),
      f("Gareth Taylor", ["ST","FW"], 79, 8, 2),
    ],
    "2010s": [
      f("Lewis Grabban", ["ST","FW"], 81, 12, 3),
      f("Joe Worrall", ["CB","DF"], 80, 2, 1),
      f("Costel Pantilimon", ["GK"], 80, 0, 0, 10),
      f("Matty Cash", ["RB","DF"], 81, 3, 4),
      f("Joe Lolley", ["RW","FW"], 80, 8, 5),
      f("Tobias Figueiredo", ["CB","DF"], 79, 1, 1),
    ],
    "2020s": [
      f("Brennan Johnson", ["RW","FW"], 84, 10, 6),
      f("Morgan Gibbs-White", ["CM","MF"], 85, 8, 8),
      f("Dean Henderson", ["GK"], 83, 0, 0, 11),
      f("Taiwo Awoniyi", ["ST","FW"], 83, 12, 3),
      f("Neco Williams", ["RB","DF"], 82, 3, 5),
      f("Murillo", ["CB","DF"], 83, 2, 1),
    ],
  },
  "Leicester City": {
    "1990s": [
      f("Gary Lineker", ["ST","FW"], 88, 18, 4),
      f("Steve Walsh", ["CB","DF"], 81, 2, 1),
      f("Kevin Pressman", ["GK"], 80, 0, 0, 10),
      f("Muzzy Izzet", ["CM","MF"], 82, 6, 6),
      f("Emile Heskey", ["ST","FW"], 83, 12, 4),
      f("Tony Cottee", ["ST","FW"], 82, 12, 3),
    ],
    "2000s": [
      f("Muzzy Izzet", ["CM","MF"], 81, 5, 5),
      f("Mladen Kristijanovic", ["GK"], 79, 0, 0, 9),
      f("Paul Dickov", ["ST","FW"], 80, 10, 3),
      f("Matt Elliott", ["CB","DF"], 79, 2, 1),
      f("Gerry Taggart", ["CB","DF"], 80, 2, 1),
      f("Brian Deane", ["ST","FW"], 80, 10, 3),
    ],
    "2010s": [
      f("Jamie Vardy", ["ST","FW"], 88, 22, 5),
      f("Riyad Mahrez", ["RW","FW"], 88, 14, 10),
      f("Kasper Schmeichel", ["GK"], 87, 0, 0, 14),
      f("Wes Morgan", ["CB","DF"], 83, 2, 1),
      f("N'Golo Kante", ["CM","MF"], 88, 2, 3),
      f("Harry Maguire", ["CB","DF"], 84, 3, 1),
    ],
    "2020s": [
      f("Jamie Vardy", ["ST","FW"], 84, 14, 4),
      f("James Maddison", ["CM","MF"], 86, 10, 10),
      f("Kasper Schmeichel", ["GK"], 84, 0, 0, 12),
      f("Youri Tielemans", ["CM","MF"], 85, 6, 8),
      f("Harvey Barnes", ["LW","FW"], 84, 10, 5),
      f("Wesley Fofana", ["CB","DF"], 84, 2, 1),
    ],
  },
  "Southampton": {
    "1990s": [
      f("Matt Le Tissier", ["CM","MF"], 88, 12, 10),
      f("Alan Shearer", ["ST","FW"], 90, 22, 4),
      f("Tim Flowers", ["GK"], 83, 0, 0, 12),
      f("Graeme Le Saux", ["LB","DF"], 84, 2, 6),
      f("Rod Wallace", ["ST","FW"], 82, 10, 4),
      f("Neil Ruddock", ["CB","DF"], 81, 3, 1),
    ],
    "2000s": [
      f("James Beattie", ["ST","FW"], 83, 12, 3),
      f("Antti Niemi", ["GK"], 82, 0, 0, 11),
      f("Marian Pahars", ["ST","FW"], 82, 10, 4),
      f("Kenny Cunningham", ["RB","DF"], 82, 2, 4),
      f("Kevin Phillips", ["ST","FW"], 84, 14, 3),
      f("Anders Svensson", ["CM","MF"], 81, 4, 5),
    ],
    "2010s": [
      f("Sadio Mane", ["LW","FW"], 87, 14, 8),
      f("Virgil van Dijk", ["CB","DF"], 88, 3, 1),
      f("Fraser Forster", ["GK"], 84, 0, 0, 12),
      f("Dusan Tadic", ["RW","FW"], 85, 10, 10),
      f("Morgan Schneiderlin", ["CM","MF"], 84, 4, 4),
      f("Graziano Pelle", ["ST","FW"], 83, 12, 4),
    ],
    "2020s": [
      f("James Ward-Prowse", ["CM","MF"], 85, 6, 8),
      f("Che Adams", ["ST","FW"], 83, 12, 3),
      f("Gavin Bazunu", ["GK"], 82, 0, 0, 10),
      f("Kyle Walker-Peters", ["RB","DF"], 83, 2, 5),
      f("Adam Armstrong", ["ST","FW"], 82, 10, 3),
      f("Jan Bednarek", ["CB","DF"], 82, 2, 1),
    ],
  },
  "Ipswich Town": {
    "1990s": [
      f("John Wark", ["CM","MF"], 82, 8, 5),
      f("Craig Forrest", ["GK"], 81, 0, 0, 10),
      f("Chris Kiwomya", ["ST","FW"], 80, 10, 3),
      f("Simon Milton", ["CM","MF"], 79, 4, 4),
      f("Frank Yallop", ["CB","DF"], 79, 2, 1),
      f("Emanuel Villa", ["ST","FW"], 78, 8, 2),
    ],
    "2000s": [
      f("Marcus Stewart", ["ST","FW"], 82, 12, 3),
      f("Matt Holland", ["CM","MF"], 81, 5, 5),
      f("Shane Supple", ["GK"], 78, 0, 0, 8),
      f("Shefki Kuqi", ["ST","FW"], 80, 10, 3),
      f("Richard Naylor", ["CB","DF"], 79, 2, 1),
      f("Jim Magilton", ["CM","MF"], 80, 5, 5),
    ],
    "2010s": [
      f("Daryl Murphy", ["ST","FW"], 80, 10, 3),
      f("Adam Webster", ["CB","DF"], 80, 2, 1),
      f("Dean Gerken", ["GK"], 78, 0, 0, 8),
      f("David McGoldrick", ["ST","FW"], 81, 10, 4),
      f("Cole Skuse", ["CM","MF"], 79, 3, 3),
      f("Luke Chambers", ["CB","DF"], 78, 2, 1),
    ],
    "2020s": [
      f("Conor Chaplin", ["ST","FW"], 82, 12, 4),
      f("Sammie Szmodics", ["CM","MF"], 81, 8, 5),
      f("Vaclav Hladky", ["GK"], 79, 0, 0, 9),
      f("Wes Burns", ["RW","FW"], 80, 8, 5),
      f("Leif Davis", ["LB","DF"], 81, 3, 6),
      f("Harry Clarke", ["CB","DF"], 80, 2, 1),
    ],
  },
  "Sunderland": {
    "1990s": [
      f("Kevin Phillips", ["ST","FW"], 86, 20, 4),
      f("Niall Quinn", ["ST","FW"], 84, 14, 5),
      f("Lionel Perez", ["GK"], 80, 0, 0, 10),
      f("Michael Gray", ["LB","DF"], 81, 3, 5),
      f("Claudio Reyna", ["CM","MF"], 83, 5, 6),
      f("Stefan Schwarz", ["CM","MF"], 82, 6, 6),
    ],
    "2000s": [
      f("Darren Bent", ["ST","FW"], 84, 14, 3),
      f("Craig Gordon", ["GK"], 84, 0, 0, 12),
      f("Kenwyne Jones", ["ST","FW"], 82, 10, 3),
      f("Lee Cattermole", ["CM","MF"], 81, 3, 3),
      f("John O'Shea", ["CB","DF"], 82, 2, 2),
      f("Jordan Henderson", ["CM","MF"], 82, 4, 4),
    ],
    "2010s": [
      f("Jermain Defoe", ["ST","FW"], 84, 14, 3),
      f("Jordan Pickford", ["GK"], 83, 0, 0, 11),
      f("Steven Fletcher", ["ST","FW"], 81, 10, 3),
      f("Yann M'Vila", ["CM","MF"], 82, 4, 4),
      f("John O'Shea", ["CB","DF"], 81, 2, 1),
      f("Fabio Borini", ["ST","FW"], 81, 10, 3),
    ],
    "2020s": [
      f("Patrick Roberts", ["RW","FW"], 81, 8, 5),
      f("Dan Neil", ["CM","MF"], 80, 4, 4),
      f("Anthony Patterson", ["GK"], 79, 0, 0, 9),
      f("Jack Clarke", ["LW","FW"], 80, 8, 4),
      f("Luke O'Nien", ["CB","DF"], 79, 2, 1),
      f("Wilson Isidor", ["ST","FW"], 80, 10, 3),
    ],
  },
};
